name: Pipeline
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PORT: '3000'
      DOCS_URL: 'https://github.com/DiegoVictor/nlv-valoriza#errors-reference'
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION_TIME: '15m'
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          npm ci
          npm run test
      - uses: codecov/codecov-action@v5
        with:
          directory: ./tests/coverage/
